name: CI

on:
  push:

permissions:
  contents: write
  actions: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build
    uses: spacelift-io/flows-community-registry/.github/workflows/build-app-version.yml@main

  release:
    name: Release
    needs: build
    uses: spacelift-io/flows-community-registry/.github/workflows/release-app-version.yml@main
